version: "3.8"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - db
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
        - './:/var/www/html:delegated'
  db:
    platform: linux/x86_64
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      PMA_PORT: 3306
    restart: always
    ports:
      - "8001:80"

volumes:
  db:
    driver: local


